services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
    expose:
      - "5432"
#    volumes:
#      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

